Add support for storage and postgrest
paust-team/shaple-flutter pull request #2
Opened 2024-02-12 05:07 UTC by 1dennispark

This PR is merged from #1 

### Changes
- add storage and postgrest service
- add simple tests for shaple client

2024-02-13 07:57 UTC, vincent-1014 requested changes

2024-02-13 07:57 UTC, vincent-1014 commented on packages/shaple/lib/src/auth_http_client.dart
> +}
ShapleClient에서 AuthHttpClient가 사용되는 부분이 없습니다.
만들어두신 이유가 무엇인가요??

2024-02-13 08:28 UTC, 1dennispark commented on packages/shaple/lib/src/auth_http_client.dart
> +}
아 제거해야 하는데 못했네요. 제거하도록 할게요.

2024-02-13 18:45 UTC, vincent-1014 requested changes

2024-02-13 18:45 UTC, vincent-1014 commented on packages/shaple_flutter/lib/src/flutter_go_true_client_options.dart
> +      pkceAsyncStorage: pkceAsyncStorage ?? this.asyncStorage,
FlutterAuthClientOptions에는 `pkceAsyncStorage`가 더이상 정의되지 않습니다.
`pkceAsyncStorage: `를 `asyncStorage: ` 로 변경하여야 할 것 같습니다.

2024-02-13 18:45 UTC, vincent-1014 commented on packages/shaple_flutter/lib/src/shaple.dart
>        );
`pkceAsyncStorage`이 `asyncStorage`로 변경되었으니,
`pkceAsyncStorage: SharedPreferencesGotrueAsyncStorage()`도 변경되어야 하지 않을까요?

2024-02-14 05:47 UTC, vincent-1014 requested changes

2024-02-14 05:47 UTC, vincent-1014 commented on packages/shaple_flutter/test/shaple_flutter_test.dart
> +import 'package:shared_preferences/shared_preferences.dart';
`SharedPreferences`를 사용하는 부분이 없습니다.
삭제되어야 할 것 같습니다.

2024-02-14 06:58 UTC, 1dennispark commented on packages/shaple_flutter/test/shaple_flutter_test.dart
> +import 'package:shared_preferences/shared_preferences.dart';
넵 삭제하겠습니다.

2024-02-14 07:53 UTC, vincent-1014 approved these changes

2024-02-14 08:57 UTC, merged